export const LOAD_FOOD = "LOAD_FOOD";
export const LOAD_LOG_FOOD = "LOAD_LOG_FOOD";
export const LOG_FOOD = "LOG_FOOD";
export const REMOVE_LOG_FOOD = "REMOVE_LOG_FOOD";
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const LOAD_FAVORITE_FOOD = "LOAD_FAVORITE_FOOD";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
export const SEVEN_DAYS_FOOD = "SEVEN_DAYS_FOOD";